# Generated by Django 4.0.1 on 2022-01-26 19:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_restaurants_restaurant_id_pizza_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='busy_until',
            field=models.TimeField(blank=True, default=datetime.datetime(2022, 1, 26, 0, 0, 1, 749039), null=True),
        ),
    ]
