# Generated by Django 4.0.1 on 2022-01-25 14:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_restaurants_busy_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analyses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_coordinate', models.FloatField(blank=True, null=True)),
                ('restaurant_id', models.PositiveIntegerField()),
                ('deliverer_id', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('route_cost', models.FloatField(blank=True, null=True)),
                ('expected_production_time', models.FloatField(blank=True, null=True)),
                ('selected_vehicle_type', models.FloatField(blank=True, null=True)),
                ('selected_vehicle_cost', models.FloatField(blank=True, null=True)),
                ('real_production', models.TimeField(default=datetime.datetime(2022, 1, 25, 0, 0, 1, 719272))),
                ('real_delivery_time', models.TimeField(default=datetime.datetime(2022, 1, 25, 0, 0, 1, 719292))),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.orders')),
            ],
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='busy_until',
            field=models.TimeField(blank=True, default=datetime.datetime(2022, 1, 25, 0, 0, 1, 716421)),
        ),
        migrations.DeleteModel(
            name='Output',
        ),
    ]
