# Generated by Django 4.0.1 on 2022-01-25 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_analyses_alter_restaurants_busy_until_delete_output'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analyses',
            old_name='order_id',
            new_name='order',
        ),
        migrations.AlterField(
            model_name='analyses',
            name='real_delivery_time',
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name='analyses',
            name='real_production',
            field=models.TimeField(default=datetime.datetime(2022, 1, 25, 0, 0, 1, 116385)),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='busy_until',
            field=models.TimeField(blank=True, default=datetime.datetime(2022, 1, 25, 0, 0, 1, 113505)),
        ),
    ]
