# Generated by Django 4.0.1 on 2022-01-26 20:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_restaurants_busy_until'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurants',
            name='restaurant_id_pizza',
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='busy_until',
            field=models.TimeField(blank=True, default=datetime.datetime(2022, 1, 26, 0, 0, 1, 131309), null=True),
        ),
    ]
