# Generated by Django 4.0.1 on 2022-01-25 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_rename_firts_route_cost_results_first_route_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyses',
            name='expected_production_time',
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name='analyses',
            name='real_production',
            field=models.TimeField(default=datetime.datetime(2022, 1, 25, 0, 0, 1, 913888)),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='busy_until',
            field=models.TimeField(blank=True, default=datetime.datetime(2022, 1, 25, 0, 0, 1, 911357)),
        ),
    ]
