# Generated by Django 4.0.1 on 2022-01-25 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_analyses_real_delivery_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyses',
            name='expected_delivery_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='busy_until',
            field=models.TimeField(blank=True, default=datetime.datetime(2022, 1, 25, 0, 0, 1, 895708)),
        ),
    ]
