# Generated by Django 4.0.1 on 2022-01-28 11:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_restaurants_busy_until_deliverers'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverers',
            name='busy_until',
            field=models.TimeField(blank=True, default=datetime.datetime(2022, 1, 28, 0, 0, 1, 505230), null=True),
        ),
        migrations.AddField(
            model_name='deliverers',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.restaurants'),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='busy_until',
            field=models.TimeField(blank=True, default=datetime.datetime(2022, 1, 28, 0, 0, 1, 502137), null=True),
        ),
    ]
