# Generated by Django 4.0.1 on 2022-01-31 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_deliverers_busy_until_deliverers_restaurant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverers',
            name='busy_until',
            field=models.TimeField(blank=True, default=datetime.datetime(2022, 1, 31, 0, 0, 1, 457013), null=True),
        ),
        migrations.AlterField(
            model_name='deliverers',
            name='orders',
            field=models.ManyToManyField(related_name='deliverers', to='orders.Orders'),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='busy_until',
            field=models.TimeField(blank=True, default=datetime.datetime(2022, 1, 31, 0, 0, 1, 453616), null=True),
        ),
    ]
